services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: plataforma-academica-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres-academico:5432/${DB_NAME}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    networks:
      - academico_net
    restart: unless-stopped

networks:
  academico_net:
    name: academico_net
    external: true